### ISSUE TITLE
Templated responses!

### ISSUE THREAD

**Issue by errornullvoid** [Heep123/BetterModMail#11]
Just had an idea! It would be great if we could configure and use templated responses, or macro's

For example, when responding to modmail, there could be a drop down menu of "macros" that would respond with certain things, like our advertising request form, or basically anything we already use copy/paste responses for. In the input box when replying to people, you could also select these by typing ##responsetemplatename and hitting enter to auto-fill the box.

that would be shweeeet.

Templated responses could also have extra meta data, such as tags to apply when a response is sent

**Comment by Glyciant** [comment]
The responses are currently a little broken, but this is actually a thing. There's a drop-down above the admin box which has some common responses. ;)
